// <auto-generated />
using System;
using BlockBreak.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlockBreak.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20230108224802_InitialHighScores")]
    partial class InitialHighScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("BlockBreak.Model.DbEntities.HighScoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HighScoreEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b0"),
                            Name = "OMG",
                            Score = 161250L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b1"),
                            Name = "WOW",
                            Score = 146300L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b2"),
                            Name = "BEN",
                            Score = 132500L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b3"),
                            Name = "ENM",
                            Score = 117750L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b4"),
                            Name = "VER",
                            Score = 103500L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b5"),
                            Name = "ROY",
                            Score = 89250L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b6"),
                            Name = "OFT",
                            Score = 75000L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b7"),
                            Name = "BBQ",
                            Score = 60750L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b8"),
                            Name = "LOL",
                            Score = 46500L
                        },
                        new
                        {
                            Id = new Guid("2d75a0f4-bac1-41b2-811d-20e7d6ee96b9"),
                            Name = "AFK",
                            Score = 32250L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
